In [1]:
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

file_path = '../data/Sustainability_report_2024_kr.pdf'

print("문서 로드중")
loader = PyPDFLoader(file_path)
docs = loader.load()
print(len(docs))

문서 로드중
83

In [3]:
# 2. 청크 나누기
splitter = RecursiveCharacterTextSplitter(
    chunk_size = 1000,
    chunk_overlap = 100
)
chunks = splitter.split_documents(docs[:20])
print(len(chunks))

48

In [5]:
# # 3. 벡터 스토어 
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain_core.prompts import ChatPromptTemplate

embeddings = OpenAIEmbeddings()
db_path = "../vectorstore/rag_eval_20"
vectorstore = Chroma.from_documents(
    documents = chunks,
    embedding = embeddings,
    persist_directory = db_path,
    collection_name = "samsung2024_eval"
)

In [6]:
# 벡터저장소가 이미 있는 상황

embedding = OpenAIEmbeddings(
    model="text-embedding-3-small"
)
persist_dir = "../vectorstore/rag_eval_20"
collection_name = "samsung2024_eval"

vectorsore = Chroma(
    persist_directory=persist_dir,
    collection_name=collection_name,
    embedding_function=embedding
)

In [7]:
# 4. retriever 구성하기
retriever = vectorstore.as_retriever(
    search_kwargs = {"k" : 5}
)

In [8]:
# 5. 프롬프트 구성하기
from langchain_core.prompts import ChatPromptTemplate

system_prompt = (
    "You are a helpful assistant. Answer strictly based on the provided context. "
    "If the answer is not in the context, say you don't know."
    "context : {context}"
)
rag_prompt = ChatPromptTemplate.from_messages([
    ("system" , system_prompt),
    ("human", "{question}")
])

In [9]:
# 6. 모델 구성하기
model = ChatOpenAI(
    model = "gpt-4.1-mini",
    temperature = 0
)

In [10]:
# 7. 아웃풋 파서
from langchain_core.output_parsers import StrOutputParser
outputparser = StrOutputParser()

In [11]:
# 8. 체인 설정
from langchain_core.runnables import RunnableLambda, RunnablePassthrough

# 문서 합치는 함수 설정
def format_docs(docs):
    return "\n\n---\n\n".join(d.page_content for d in docs)

# 체인만들기
rag_chain = (
    {"context" : RunnableLambda(lambda x : x["question"]) | retriever | format_docs,
     "question" :RunnablePassthrough()
     }
     | rag_prompt
     | model
     | outputparser
)

In [12]:
rag_chain.invoke({"question" :"삼성전자의 전망은?"})

'삼성전자는 어려운 대내외 환경 속에서도 지속 성장을 위해 역대 최고 수준의 연구개발 투자(28.3조원)와 전략적 시설투자(53.1조원)를 통해 기술 리더십을 강화하고 중장기 수요에 대응하고 있습니다. 또한, 글로벌 공시규제 프레임워크에 맞춰 지속가능경영 이슈를 발굴하고 관리 체계와 전략, 이행 활동을 충실히 수행하며, 환경, 사회, 경제적 리스크와 지정학적 불확실성 속에서도 지속가능성을 사업경쟁력과 기술혁신의 원동력으로 삼아 새로운 도약과 발전을 모색하고 있습니다. 따라서 삼성전자는 지속가능성을 기반으로 한 기술 혁신과 경영 활동을 통해 앞으로도 지속적인 성장과 발전을 기대하고 있습니다.'

In [ ]:
# 9. 평가용 데이터 불러오기
import pandas as pd

csv_path = "../data/report_2024_text.csv"
df = pd.read_csv(csv_path)
df.head()

,user_input,reference_contexts,reference,synthesizer_name
0,What initiatives has the company undertaken in...,"[""지속가능한 미래를 위한 노력을 계속해 \n왔습니다. 2050년 탄소중립을 통해 ...","In 인도, the company has transitioned 100% of th...",single_hop_specific_query_synthesizer
1,What are the core values established by 삼성전자 f...,['삼성전자 지속가능경영보고서 2024\n05\nOur Company Appendi...,"삼성전자는 경영철학을 반영한 5가지 핵심가치를 수립하였고, 이를 세부원칙과 행동지침...",single_hop_specific_query_synthesizer
2,How does DRAM fit into Samsung Electronics' bu...,['Our Company AppendixMateriality Assessment F...,DRAM is part of Samsung Electronics' Device So...,single_hop_specific_query_synthesizer
3,What are the financial results for SDC in 2023?,"['매출\n169조 9,923억 원\n영업이익\n14조 3,847억 원 네트워크\n...",The financial results for SDC in 2023 indicate...,single_hop_specific_query_synthesizer
4,삼성전자는 어떻게 이해관계자와 소통하나요?,['삼성전자 지속가능경영보고서 2024\n06\nOur Company Appendi...,삼성전자는 이해관계자와의 커뮤니케이션을 위해 지속가능경영 웹사이트를 통해 관련 정보...,single_hop_specific_query_synthesizer

- user_input : 질문
- reference_contexts : 예상되는 답변을 만들기위해 참고한 contexts
- reference : 예상되는 답변
***
- user_input : 질문
- retrieved_contexts : 검색한 자료 -> 리스트
- response : 실제 답변

In [16]:
# for 문으로 구현하기
answer = []
contexts = []
for question in df['user_input']:
    docs = retriever.invoke(question)
    ctx_list = []
    for d in docs:
        ctx_list.append(d.page_content)
    contexts.append(ctx_list)

In [17]:
contexts

[['A Journey Towards  \na Sustainable Future\n삼성전자 지속가능경영보고서 2024',
  '· 업종 간 협력\n·  기후 대응을 포함한  \nUN SDGs에 대한 기여\n·  투명하고 신속한 정보 공개\n·  기업 간담회\n·  NGO 미팅\n·  이해관계자 포럼\n·  시민사회 - 경영진 간담회\n·  노동인권 이해관계자 워크샵\n·  지속가능경영 웹사이트\n· 산업협회\n·  글로벌 NGO 대상 의견 수렴\n·  RBA\n1)\n, RMI\n2)\n, BSR\n3)\n 활동\n1) Responsible Business Alliance\n2) Responsible Minerals Initiative\n3) Business for Social Responsibility\n·  UNGC\n1)\n·  ACEC\n2)\n, SCC\n3)\n 활동\n1) United Nations Global Compact\n2) Asia Clean Energy Coalition\n3) Semiconductor Climate Consortium\n정부 ·  간접 경제효과(투자, 고용 등 파생효과)\n·  공정거래\n·  안전·보건\n·  컴플라이언스\n·  기업윤리\n·  정책 간담회\n·  국회\n·  정책수립 공청회\n·  정책자문기구\n·  지속가능경영 웹사이트\n·  정부와 협업하여 중소기업 지원 프로그램 운영 ·  정부와 협업하여 벤처투자 창구 설립·운영\n언론 ·  주요 제품/사업 실적 및 전략\n·  투자, R&D, M&A,  \n신사업 등 미래 성장 전략 \n·  탄소중립 등 ESG 추진 성과\n·  인/노사, 환경안전, 특허,  \n제품·서비스 품질 등\n·  보도자료\n·  지속가능경영 웹사이트\n·  삼성전자 반도체 뉴스룸\n·  삼성전자 뉴스룸\n· 미디어 간담회\n·  글로벌 IT 전시회·신제품 발표 취재지원\n·  미디어데이 개최\n·  기자회견\n·  인터뷰\n·  기획홍보\n Our Company',
  'A Journey Towards  \na Sustainable Future\n삼성전자 지속가능경영보고서 2024\nCEO 메시지\n회사 소개\n이해관계자 소통\nOur Company\n04\n05\n06\n준법과 윤리경영\nPrinciple\n53\n중대성 평가\nMateriality Assessment\n08\n임직원\n공급망\n사회공헌\n개인정보보호/보안\n고객의 안전/품질\nPeople\n31\n39\n45\n48\n50\n경제성과\n사회성과\n환경성과\n지역별 수자원 현황   \n사업부문별 환경성과\nFacts & Figures\n56\n57\n62\n65\n66\n독립된 인증인의 인증보고서\nScope 1, 2 온실가스 배출량 검증 의견서\nScope 3 온실가스 배출량 검증 의견서\nGRI Index\nTCFD 대조표\nSASB 대조표\n전사차원의 기후변화 대응 협력 활동\nAbout This Report\nAppendix\n70\n71\n72\n74\n77\n79\n81\n82\n[DX부문] \n추진체계 및 주요성과\n기후변화\n자원순환\n수자원 및 오염물질\n[DS부문]  \n추진체계 및 주요성과 \n기후변화\n수자원\n폐기물\n오염물질\nPlanet\n12\n13\n15\n17\n19\n20\n23\n26\n28\n삼성전자 지속가능경영보고서 2024 02Our Company AppendixMateriality Assessment Facts & Figures PrinciplePlanet People',
  "대한 관심 또한 지속 고조되고 있습니다. \n삼성전자는 이러한 추세에 맞춰 지속가능한 미래를 위한 노력을 계속해 \n왔습니다. 2050년 탄소중립을 통해 글로벌 기후위기 극복 노력에 \n동참하고, 자원의 순환성을 극대화하여 순환경제 구축 에 기여하며, \n기술혁신을 통해 환경난제 해결에 도전하는 내용의 '新환경경영전략'을 \n2022년 9월에 발표하였습니다. \n2030년 탄소중립을 목표로 하는 DX부문에서는 미국, 유럽, 중국에 이어 \n한국, 베트남, 인도, 브라 질을 포함한 글로벌 주요 제조사업장의 사용 \n전력을 재생에너지로 100% 전환하였으며, 2023년말 기준, 총 93.4%\n의 재생에너지 전환 실적을 기록하였습니다. 또한 자원순환형 소재 확대 \n로드맵에 맞춰, 당사가 구매한 제품 내 플라스틱 부품 25%에 재생레진을 \n적용하였습니다. \nDS부문에서는 2050년 탄소중립 달성을 위해 2023년 공정가스 처리시설\n(RCS) 16대를 4개 라인에 신규 설치하고, LNG 폐열 회수 시스템을 확대 \n적용하여 온실가스 배출 저감을 위해 노력했습니다. 또한 2030년까지 \n용수 취수량을 2021년 수준으로 절 감하는 것을 목 표로 하고 있으며, \n국제수자원관리동맹(AWS)으로부터 기흥/화성, 평택, 중국 시안 사업장에 \n대해 최고 등급인 ' 플래티넘' 인증을 획득하여 수자원 관리 체계의 \n우수성을 입증 받았습니다. 아울러, 폐기물 발생량 저감을 위해 2024년 \n3월, 웨이퍼박스 등 9건에 대해 환경부 순환자원 인정을 추가 취득하여 \n현재까지 총 49건을 순환자원으로 인정받았고 매년 품목을 확대해나가고 \n있습니다.\n사회 분야에서는 지난 2023년 2월 발표한 글로벌 인권원칙에 연계하여, \n글로벌 고충처리 정책 을 2024년 4월 제정, 고충  접수 채널 운영과 \n접수된 고충의 처리 원칙에 대한 기준을 수립하였고, 공급망 관리에 \n있어서는 비제조 분야 및 리스크 분석에 따라 제조 분야 2차 협력회사로",
  '삼성전자 지속가능경영보고서 2024\n10\nOur Company AppendixMateriality Assessment Facts & Figures PrinciplePlanet People\n2024년 중대 주제 UN SDGs 추진체계\n(거버넌스)\n추진방향\n(전략)\n리스크 관리\n(정책)\n활동\n(주요성과)\n기후변화 및 에너지\n‧  이사회 산하 지속가능경영위원회에서 \n환경경영을 포함한 지속가능경영 방향성과 \n이행 성과 감독 실시\n‧   CEO 주관 지속가능경영협의체 및 환경경영\nTF(유관조직 간)에서 현안 논의 및 의사결정\n·  2030년까지 공정가스 저감, 수자원 보존 등 \n환경경영 과제에 총 7조원 이상 투자\n·  DX부문 : 2030년까지 탄소중립(Scope 1, 2)달성 \n·  DS부문 : 2050년까지 탄소중립(Scope 1, 2) 달성 \n· 新환경경영전략 수립 및 이사회 차원의 결의\n·  이행과제 실행을 위한 전사 환경경영 TF/\n탄소중립위원회 운영\n·  직접 배출 감축, 재생에너지 확대,  \n외부 온실가스 감축사업 실시\n수자원\n·  DX부문 : 2030년까지 용수 사용량 100% 환원\n·  DS부문 : 2030년까지 국내 사업장 취수량 증가 제로화\n·  新환경경영전략 수립 및 이사회 차원의 결의\n·  이행과제 실행을 위한 전사 환경경영 TF/\n탄소중립위원회 운영\n·  수자원 리스크 평가 및 지역별 대응전략 수립\n·  국내 사업장 AWS\n1)\n 인증 취득 범위 확대 \n1) Alliance for Water Stewardship \n자원순환 및 폐기물\n·  DX부문 : 2050년까지 모든 플라스틱 부품 재생레진 적용\n·  DS부문 : 국내 사업장 폐기물 재활용률 99.9% 달성\n·  新환경경영전략 수립 및 이사회 차원의 결의\n·  이행과제 실행을 위한 전사 환경경영 TF/\n탄소중립위원회 운영\n·  폐제품 수거 체계 운영, 사업장 폐기물  \n매립 제로 인증 획득\n임직원 - 근로조건\n·  이사회 산하 지속가능경영위원회, CEO \n주관 지속가능경영협의체와 노동인권'],
 ['A Journey Towards  \na Sustainable Future\n삼성전자 지속가능경영보고서 2024\nCEO 메시지\n회사 소개\n이해관계자 소통\nOur Company\n04\n05\n06\n준법과 윤리경영\nPrinciple\n53\n중대성 평가\nMateriality Assessment\n08\n임직원\n공급망\n사회공헌\n개인정보보호/보안\n고객의 안전/품질\nPeople\n31\n39\n45\n48\n50\n경제성과\n사회성과\n환경성과\n지역별 수자원 현황   \n사업부문별 환경성과\nFacts & Figures\n56\n57\n62\n65\n66\n독립된 인증인의 인증보고서\nScope 1, 2 온실가스 배출량 검증 의견서\nScope 3 온실가스 배출량 검증 의견서\nGRI Index\nTCFD 대조표\nSASB 대조표\n전사차원의 기후변화 대응 협력 활동\nAbout This Report\nAppendix\n70\n71\n72\n74\n77\n79\n81\n82\n[DX부문] \n추진체계 및 주요성과\n기후변화\n자원순환\n수자원 및 오염물질\n[DS부문]  \n추진체계 및 주요성과 \n기후변화\n수자원\n폐기물\n오염물질\nPlanet\n12\n13\n15\n17\n19\n20\n23\n26\n28\n삼성전자 지속가능경영보고서 2024 02Our Company AppendixMateriality Assessment Facts & Figures PrinciplePlanet People',
  'A Journey Towards  \na Sustainable Future\n삼성전자 지속가능경영보고서 2024',
  '삼성전자 지속가능경영보고서 2024\n05\nOur Company AppendixMateriality Assessment Facts & Figures PrinciplePlanet People\n회사소개\nAbout Us\n삼성전자주식회사(이하 삼성전자)는 인재와 기술을 바탕으로 최고의 제품과 서비스를 창출하여 인류사회에 공헌하는 글로벌 초일류기업을 지향합니다. \n이를 위해 삼성전자의 경영철학을 반영한 5가지 핵심가치 를 수립하였고, 핵심가치를 세부원칙과 행동지침 으로 구체화하여 삼성전자 임직원이 \n지켜야 할 글로벌 행동규범(Global Code of Conduct) 을 제정하였습니다. 삼성전자는 조직문화에 5가지 핵심가치를 내재화하고 글로벌 행동규범을 \n모든 경영활동의 기준으로 삼아 지속적으로 성장해갈 것입니다. \n사업부문 및 글로벌 네트워크 소개\n삼성전자는 제품 특성에 따라 DX(Device eXperience)와 DS(Device Solutions) 2개 부문으로 나뉘어 독립적으로 운영되고 있습니다. DX부문은 \n스마트폰, 네트워크 시스템, 컴퓨터, TV, 냉장고, 세탁기, 에어컨, 의료기기 등 완제품을 생산/판매하고 있으며, DS부문은 메모리 반도체 사업, Foundry \n사업, System LSI 사업으로 구성되어 DRAM, NAND Flash, 모바일AP 등의 반도체 부품을 생산/판매하고 있습니다. 삼성전자는 2023년 말 기준 전 \n세계에 232개의 생산거점, 판매거점, R&D 센터, 디자인 센터를 보유하고 있습니다.\n Our Company\n매출\n169조 9,923억 원\n영업이익\n14조 3,847억 원 네트워크\nMobile eXperience 영상디스플레이 생활가전\n의료기기\n매출\n66조 5,945억 원\n영업이익\n△14조 8,795억 원\nFoundry System LSI\n주요 사업부\nDevice eXperienceDX\nDS Device Solutions\n메모리\n※ 상기 매출과 영업이익은 2023년 실적을 기준으로, SDC, Harman을 제외하고 작성했습니다.',
  "접수된 고충의 처리 원칙에 대한 기준을 수립하였고, 공급망 관리에 \n있어서는 비제조 분야 및 리스크 분석에 따라 제조 분야 2차 협력회사로 \n근로환경 관리 범위를 확대하고 있습니다. 또한 2023년 3월 자회사 형 \n장애인표준사업장 주식 회사 '희망별숲'을 개소하여, 발달 장애인들이 \n삼성전자 임직원에게 제공되는 쿠키 , 머핀 등 제과 제품을 만들 고 \n있습니다. 제과 분야를 시작으로 발달장애인들에게 안정적인 일자리를 \n제공할 예정입니다.\n무엇보다 올해 지속가능경영보고서는 글로벌 공시규제 프레임워크에 \n맞춰, 당사의 주요 지속가능경영 이슈를 발 굴하고, 주요 이슈의 관리 \n체계와 전략, 이행 활동과 현황을 충 실히 전달 하고자 구성하였으며, \n삼성전자의 지속가능경영 웹사이트와도 긴밀히 연계되도록 하였습니다. \n삼성전자는 환경, 사회, 경제적 리스크 와 지정학적 불확실성이 일상이 \n되어버린 시대를 경험 하면서, 지속가능성을 삼성전자가 나아가야할 \n방향의 흔들리지 않는 지표이자, 사업경쟁력과 기술혁신의 원동력으로 \n삼고 있습니다. 어려움은 위대함을 키운다(Difficulty is the Nurse of \nGreatness)는 격언처럼, 삼성전자는 지속가능성을 통해 새로운 도약을 \n모색하고, 더욱 발전하는 모습으로 이해관계자 여러분의 기대에 부응하기 \n위해 최선을 다하겠습니다. \n감사합니다.\n삼성전자주식회사\n 대표이사 부회장\n한종희\n삼성전자주식회사 \nDS부문장 부회장\n전영현\n Our Company",
  '삼성전자 지속가능경영보고서 2024\n09\nOur Company AppendixMateriality Assessment Facts & Figures PrinciplePlanet People\nStep 4. 중대 주제 선정\n삼성전자는 평가 설문 응 답에 대한 정량적 분 석 결과와 정성적 분 석 \n결과를 종합해 기후변화 및 에너지, 수자원, 자원순환 및 폐기물, 임직원-\n근로조건, 공급망, 정보보호 및 보안, 제품 품질 및 안전, 윤리경영 등 8개 \n중대 주제를 선정했습니다. 각 부문별로 업의 특성이 상이한 이유로 인해 \n부문별로 환경에 대한 중대 이슈를 추가 도출하였습니다. DX부문의 주요 \n환경 이슈는 기후변화 및 에 너지, 수자원, 자원순환 및 폐기물이며 DS\n부문의 주요 환경 이슈는 기후변화 및 에너지, 수자원, 자원순환 및 폐기물, \n오염물질로 확인되었습니다. 도출된 중대 주제는 경영진 검토를 거 쳐 \n최종적으로 이사회 산하 지속가능경영위원회에 보고되었습니다.\n경영진 인터뷰 결과\n정성적 분석 결과\n·  정량적 분석 및 정성적 분석 결과를 종합하여 최종 중대 선정\n1)\n·  환경 분야 3개, 사회 분야 4개, 거버넌스 분야 1개 주제 등 8개 중대 주제 \n선정 \n영향·위험·기회 파악\n정량적 분석 결과\n재무 위험/\n기회 평가 결과\n환경/사회 \n영향 평가 결과\n1)  전기 평가 결과와 대비하여 정보보호 및 보안, 제품 품질 및 안전, 윤리경영이 새로운 \n중대 주제로 도출\nStep 2. 영향/위험/기회 파악\n삼성전자는 1차로 도출된 13개 ESG 주제의 환경/사회 영향과 재무 위험/\n기회를 파악하였습니다. 먼저 1차로 도출된 주제와 관련한 규제, 미디어, \n지속가능경영 홈페이지, 지속가능경영보고서 서술 내용과 더불어 고객사, \n투자자, 평가사 등 주요 이해관계자의 요구사항 을 포함한 식별 근거를 \n마련하고 유관 사업 활동을 분석하였습니다. 이후 각 활동과 관련성이 높은 \n밸류체인의 사업 활동이 환경과 사회에 미치는 영향을 파악하였습니다.'],
 ['삼성전자 지속가능경영보고서 2024\n05\nOur Company AppendixMateriality Assessment Facts & Figures PrinciplePlanet People\n회사소개\nAbout Us\n삼성전자주식회사(이하 삼성전자)는 인재와 기술을 바탕으로 최고의 제품과 서비스를 창출하여 인류사회에 공헌하는 글로벌 초일류기업을 지향합니다. \n이를 위해 삼성전자의 경영철학을 반영한 5가지 핵심가치 를 수립하였고, 핵심가치를 세부원칙과 행동지침 으로 구체화하여 삼성전자 임직원이 \n지켜야 할 글로벌 행동규범(Global Code of Conduct) 을 제정하였습니다. 삼성전자는 조직문화에 5가지 핵심가치를 내재화하고 글로벌 행동규범을 \n모든 경영활동의 기준으로 삼아 지속적으로 성장해갈 것입니다. \n사업부문 및 글로벌 네트워크 소개\n삼성전자는 제품 특성에 따라 DX(Device eXperience)와 DS(Device Solutions) 2개 부문으로 나뉘어 독립적으로 운영되고 있습니다. DX부문은 \n스마트폰, 네트워크 시스템, 컴퓨터, TV, 냉장고, 세탁기, 에어컨, 의료기기 등 완제품을 생산/판매하고 있으며, DS부문은 메모리 반도체 사업, Foundry \n사업, System LSI 사업으로 구성되어 DRAM, NAND Flash, 모바일AP 등의 반도체 부품을 생산/판매하고 있습니다. 삼성전자는 2023년 말 기준 전 \n세계에 232개의 생산거점, 판매거점, R&D 센터, 디자인 센터를 보유하고 있습니다.\n Our Company\n매출\n169조 9,923억 원\n영업이익\n14조 3,847억 원 네트워크\nMobile eXperience 영상디스플레이 생활가전\n의료기기\n매출\n66조 5,945억 원\n영업이익\n△14조 8,795억 원\nFoundry System LSI\n주요 사업부\nDevice eXperienceDX\nDS Device Solutions\n메모리\n※ 상기 매출과 영업이익은 2023년 실적을 기준으로, SDC, Harman을 제외하고 작성했습니다.',
  'DS Device Solutions\n메모리\n※ 상기 매출과 영업이익은 2023년 실적을 기준으로, SDC, Harman을 제외하고 작성했습니다.\n지역총괄\n1)\n판매거점\n2)\n생산거점 구매 센터\n15 109 32 6\n1) 내부관리 기준에 따른 지역구분  2) 판매법인, 지점 등  3) 물류법인, IP 오피스 등  4) 당사 제품 생산용 부품을 공급하는 기업 \n임직원 267 ,860명 연구개발비 28.3조 원운영국가 76개국협력회사\n4)\n 2,515개\nR&D 센터 디자인 센터 기타\n 3)\n합계\n40 7 23 232',
  "접수된 고충의 처리 원칙에 대한 기준을 수립하였고, 공급망 관리에 \n있어서는 비제조 분야 및 리스크 분석에 따라 제조 분야 2차 협력회사로 \n근로환경 관리 범위를 확대하고 있습니다. 또한 2023년 3월 자회사 형 \n장애인표준사업장 주식 회사 '희망별숲'을 개소하여, 발달 장애인들이 \n삼성전자 임직원에게 제공되는 쿠키 , 머핀 등 제과 제품을 만들 고 \n있습니다. 제과 분야를 시작으로 발달장애인들에게 안정적인 일자리를 \n제공할 예정입니다.\n무엇보다 올해 지속가능경영보고서는 글로벌 공시규제 프레임워크에 \n맞춰, 당사의 주요 지속가능경영 이슈를 발 굴하고, 주요 이슈의 관리 \n체계와 전략, 이행 활동과 현황을 충 실히 전달 하고자 구성하였으며, \n삼성전자의 지속가능경영 웹사이트와도 긴밀히 연계되도록 하였습니다. \n삼성전자는 환경, 사회, 경제적 리스크 와 지정학적 불확실성이 일상이 \n되어버린 시대를 경험 하면서, 지속가능성을 삼성전자가 나아가야할 \n방향의 흔들리지 않는 지표이자, 사업경쟁력과 기술혁신의 원동력으로 \n삼고 있습니다. 어려움은 위대함을 키운다(Difficulty is the Nurse of \nGreatness)는 격언처럼, 삼성전자는 지속가능성을 통해 새로운 도약을 \n모색하고, 더욱 발전하는 모습으로 이해관계자 여러분의 기대에 부응하기 \n위해 최선을 다하겠습니다. \n감사합니다.\n삼성전자주식회사\n 대표이사 부회장\n한종희\n삼성전자주식회사 \nDS부문장 부회장\n전영현\n Our Company",
  '삼성전자 지속가능경영보고서 2024\n15\nOur Company AppendixMateriality Assessment Facts & Figures PrinciplePlanet People\n자원순환\nCircular Economy\n Planet / DX부문\n추진방향\nDX부문은 원 료부터 생산/폐기/재활용까지 제품의 모 든 주기에 걸 쳐 \n자원순환성을 높이는 과제를 하고 있습니다. 재활용 소재로 제품을 만들고 \n다 쓴 제품을 수거해 자원을 추출한 뒤 다시 이를 제품의 재료로 사용하는 \n‘자원 순환 체계’를 추구합니다. 또한 제품을 더 오래 쓸 수 있는 방법을 \n연구하고 적용하여 제품이 환경에 미치는 영향을 최소화하고자 합니다. \n이를 위해 일부 제품에서는 내구성, 수리 용이성을 높이고, 주기적인 \n소프트웨어 업그레이드를 지원하며, 삼성 케어 플러스(Samsung Care+) \n프로그램을 통해 파손, 수리에 대한 소비자 부담을 덜어주고 제품 수명 \n연장에 기여합니다.\n자원순환형 소재 확대\n‧  플라스틱 폐기물 문제 해결을 위한 폐어망 \n재활용 혁신 기술 개발\n‧  재활용 알루미늄/유리 등 재생/재활용 소재 \n지속적 확대\n‧  2030년까지 DX부문이 구매하는 제품 내 \n플라스틱 부품의 50%, 2050년까지 모든 \n플라스틱 부품에 재생레진 적용\n폐제품 수거 체계 운영\n‧  폐제품이 새로운 제품의 재료가 되어 재활용 \n될 수 있도록 70여개 국가에서 폐전자제품\n(e-Waste) 수거/재활용 체계 운영\n‧  2030년까지 폐제품 수거 체계를  \n180여 개국으로 확대\n‧  2030년까지 1,000만 톤, 2050년까지 \n2,500만 톤의 폐전자제품 수거\n사업장 폐기물 매립 제로 인증\n‧  폐기물 재활용 증대 목적의 폐기물 매립 제로화 정책 수립\n‧  모든 제조사업장에 대해 글로벌 환경안전 인증기관 UL의 ‘폐기물 매립 \n제로 인증\n1)\n’ 취득 계획\n‧  2025년까지 DX부문 제조사업장 최고등급(플래티넘) 인증 취득',
  '삼성전자 지속가능경영보고서 2024\n16\nOur Company AppendixMateriality Assessment Facts & Figures PrinciplePlanet People\n폐제품 수거 체계 운영 \nDX부문은 한국을 포 함한 전 세계 70여 개국에서 브랜드에 관계 없이 \n폐제품을 수거하기 위해 다양한 재활용 프로그램을 운영하고 있습니다. \n국가별 특성을 고려해 리사이클링센터를 직접 운영하거나 재활용 협회 \n또는 재활용 업체와 협업해 폐전자제품 회수/재활용 프로그램을 운영하고 \n있습니다.\n2009년부터 2023년까지 누적 629.7만 톤의 폐전자제품을 회수했습니다. \n앞으로 2030년까지 제품을 판매하고 있는 모든 나라인 180여 개국으로 \n폐제품 수거 체계를 확대하고, 2009년부터 누적으로 2030년 1,000만 톤, \n2050년 2,500만 톤의 폐전자제품을 수거할 계획입니다.\n제품 수명 연장 활동\n제품의 교체 주기가 짧 아질수록 소모되는 자원도, 배출되는 탄소도 \n늘어나기에 우리 제품이 환경에 미치는 영향을 고려해 제품을 더 오래 쓸 \n수 있는 방법을 연구하고 적용합니다. 내구성, 수리 용이성, 소프트웨어 \n업그레이드 외에도 미국 CRN(Certified Re-Newed) 프로그램\n1)\n을 \n통해 제품 수명 연장에 기여하고 있습니다.\n1) 운영국가 : 미국, 영국, 프랑스(2024년 3월 기준)\n자원 재활용 기술 연구\nDX부문은 자원순환 극대화를 위해 2022년 7월 소재 재활용 및 기술과 \n제품 적용을 연구하는 조직인 ‘순환경제연구소 ’를 설립 했습니다. \n순환경제연구소는 재활용 소재 개발, 폐기물 자원화 기술 연구 등을 통해 \n궁극적으로 제품의 모든 소재를 재활용 소재로 대체하는 것을 목 표로 \n국내외 연구기관 및 기업들과 협업을 추진하고 있습니다.\n사업장 폐기물 매립 제로 인증\nDX부문은 소중한 자원을 재활용하고, 환경 영 향을 줄이기 위해 모 든 \n제조사업장에서 폐기물 매립 제로 인증 취득 을 목표로 수립했습니다.'],
 ['DS Device Solutions\n메모리\n※ 상기 매출과 영업이익은 2023년 실적을 기준으로, SDC, Harman을 제외하고 작성했습니다.\n지역총괄\n1)\n판매거점\n2)\n생산거점 구매 센터\n15 109 32 6\n1) 내부관리 기준에 따른 지역구분  2) 판매법인, 지점 등  3) 물류법인, IP 오피스 등  4) 당사 제품 생산용 부품을 공급하는 기업 \n임직원 267 ,860명 연구개발비 28.3조 원운영국가 76개국협력회사\n4)\n 2,515개\nR&D 센터 디자인 센터 기타\n 3)\n합계\n40 7 23 232',
  '삼성전자 지속가능경영보고서 2024\n10\nOur Company AppendixMateriality Assessment Facts & Figures PrinciplePlanet People\n2024년 중대 주제 UN SDGs 추진체계\n(거버넌스)\n추진방향\n(전략)\n리스크 관리\n(정책)\n활동\n(주요성과)\n기후변화 및 에너지\n‧  이사회 산하 지속가능경영위원회에서 \n환경경영을 포함한 지속가능경영 방향성과 \n이행 성과 감독 실시\n‧   CEO 주관 지속가능경영협의체 및 환경경영\nTF(유관조직 간)에서 현안 논의 및 의사결정\n·  2030년까지 공정가스 저감, 수자원 보존 등 \n환경경영 과제에 총 7조원 이상 투자\n·  DX부문 : 2030년까지 탄소중립(Scope 1, 2)달성 \n·  DS부문 : 2050년까지 탄소중립(Scope 1, 2) 달성 \n· 新환경경영전략 수립 및 이사회 차원의 결의\n·  이행과제 실행을 위한 전사 환경경영 TF/\n탄소중립위원회 운영\n·  직접 배출 감축, 재생에너지 확대,  \n외부 온실가스 감축사업 실시\n수자원\n·  DX부문 : 2030년까지 용수 사용량 100% 환원\n·  DS부문 : 2030년까지 국내 사업장 취수량 증가 제로화\n·  新환경경영전략 수립 및 이사회 차원의 결의\n·  이행과제 실행을 위한 전사 환경경영 TF/\n탄소중립위원회 운영\n·  수자원 리스크 평가 및 지역별 대응전략 수립\n·  국내 사업장 AWS\n1)\n 인증 취득 범위 확대 \n1) Alliance for Water Stewardship \n자원순환 및 폐기물\n·  DX부문 : 2050년까지 모든 플라스틱 부품 재생레진 적용\n·  DS부문 : 국내 사업장 폐기물 재활용률 99.9% 달성\n·  新환경경영전략 수립 및 이사회 차원의 결의\n·  이행과제 실행을 위한 전사 환경경영 TF/\n탄소중립위원회 운영\n·  폐제품 수거 체계 운영, 사업장 폐기물  \n매립 제로 인증 획득\n임직원 - 근로조건\n·  이사회 산하 지속가능경영위원회, CEO \n주관 지속가능경영협의체와 노동인권',
  '삼성전자 지속가능경영보고서 2024\n04\nOur Company AppendixMateriality Assessment Facts & Figures PrinciplePlanet People\nCEO 메시지\nMessage from \nOur CEO\n주주, 고객, 협력회사, 그리고 임직원 여러분,\n2023년은 고금리와 인플레이션, 지정학적 이슈 등 매우 불확실한 \n거시경제 환경과 함께, 메모리 산업 부진과 다양한 제품군에서의 경쟁 \n심화로 삼성전자에게 매우 어려운 한 해였습니다. 이토록 대내외적으로 \n어려운 환경에서도 지속 성장의 기반 마련을 위해 역대 최고 수준의 28.3\n조원을 연구개발에 투자하고, 53.1조원 수준의 전략적 시설투자로 기술 \n리더십을 강화하며 중장기 수요에 미리 대응할 수 있었던 것은 삼성전자를 \n아껴주시는 이해관계자 여러분의 관심과 격려 덕분입니다. 다시 한 번 \n깊이 감사 드립니다.\n급격한 변화를 겪고 있는 경제 상황에 맞춰, 기업의 지속가능경영 \n분야에서도 많은 변화가 일어나고 있습니다. 특히 기업의 지속가능경영 \n활동 정보 공개는 글로벌 비재무정보 공시 제도의 확산에 맞춰, 새로운 \n국면을 맞고 있습니다. 국제회계기준재단(IFRS Foundation)이 2023년 \n6월 지속가능성 지표를 확정한 것을 시작으로, EU의 지속가능성 보고지침\n(CSRD)과 미국 증권거래위원회(SEC) 기후공시 기준 역시 세부 내용을 \n순차적으로 확정하며 ESG 정보의 의무 공시 시대가 열리고 있습니다.\n이와 함께, EU 탄소국경조정제도(CBAM)와 EU 배터리규제 등을 통한 \n환경규제 역시 지속 강화되는 추세이고, 독일에서는 공급망의 인권과 \n근로환경 관리를 의무화하는 공급망실사법이 2023년 발효되었으며, \n2024년 5월 EU 공급망 실사지침(CSDDD)이 확정되는 등 인권 분야에 \n대한 관심 또한 지속 고조되고 있습니다. \n삼성전자는 이러한 추세에 맞춰 지속가능한 미래를 위한 노력을 계속해',
  'A Journey Towards  \na Sustainable Future\n삼성전자 지속가능경영보고서 2024',
  '삼성전자 지속가능경영보고서 2024\n13\nOur Company AppendixMateriality Assessment Facts & Figures PrinciplePlanet People\n기후변화\nClimate Change\n Planet / DX부문\n추진방향\nDX부문은 지난  2022년에 발표한 新 환경경영전략에 맞춰 2030년  \n까지 직∙ 간접(Scope 1, 2) 탄소 순배출을 제로화하는 탄소중립을 \n달성할 계획입니다. 이를 위해 공정 에너지 효율 제고를 통해 온실가스 \n직접배출을 최소화하고 재생 에너지 사용을 확대하고 있습니다. 또한 \n제품의 물류, 판매, 사용 등 사업장을 넘 어 전 밸류체인에 걸쳐 다양한 \n온실가스 감축 과제를 추진하고 있습니다.\n기후변화 전략\n리스크 관리\nDX부문은 기후변화와 관련된 리스 크의 실질적인 재무적 또는 전략적 \n영향을 규명하고, 이슈의 중요도와 사업에 미치는 영향에 따라 대응전략을 \n수립하고 의사 결정에 반영합니다. 리스크는 글로벌 기후체제, 지역별 \n규제 강화, 시장의 변화, 이해관계자 요구사 항, 물리적 환경 변화 등을 \n포함합니다. 특히, 국내 제조사업장은 배출권거래제 기반으로 온실가스 \n배출량 관리, 산정, 배출권 제출의 법적의무를 이행하고 있습니다. \n국가 온실가스 감 축목표(NDC\n1)\n)에 따라 배출권거래제 해 당 기업에게 \n부과되는 온실가스 감축목표는 점차 강화될 것으로 예상하고 있습니다.\n단기적으로는 탄소배출권 가격 상승과 에너지 고효율 기술 도입에 따른 \n투자비 증가, 기상이변 대응을 위한 투자, 복구비용 증가를 잠재적인 \n리스크로 보고 있으며, 외부 탄소배출권 확보를 통한 탄소가격 민 감도 \n완화와 에너지 고효율 설비 도입에 따른 에너지 비용 절감을 기회요인으로 \n인식하고 있습니다. \n중기적으로는 소비자 들의 소비 패턴 변화와 친 환경 제품 선 호 등을 \n기회요인으로 예상하며, 기온 상승  및 수자원 고갈  등과 같 은 물리적 \n영향을 장기적 리스크로 예상하고 있습니다.'],
 ['기회 등에 대해 논의하였습니다. 삼성전자는 참 석한 이해관계자들과의 미팅을 \n통해 삼성전자의 지속가능경영 성과를 공유하고, 유럽 및 글로벌 이해관계자들의 \n요청사항을 파악하였습니다. 삼성전자는 이러한 의견을 지속가능경영 활동 추진 \n시 반영하고 그 성과를 지속 소통해 나가겠습니다.\n법/규제 사항\n외부 공시 내용 \n(미디어, 홈페이지, \n지속가능경영보고서 등)\n이해관계자 요구사항 \n(고객사, 투자자, \n협력회사, 평가사 등)\n·  ESG 주제 관련 회사의 활동이 환경/\n사회에 미치는 영향\n·  영향의 특성에 따라 긍정과 부정, \n실재와 잠재적 영향으로 분류\n식별 근거\n환경/ \n사회  \n영향\n·  ESG 주제 관련 외부 요인이 회사에 \n재무적으로 미치는 영향\n·  영향의 특성에 따라 위험과 기회로 분류\n재무 \n위험/\n기회\n영향·위험·기회 파악\n구분 평가 기준\n환경/\n사회 \n영향\n규모 각 환경/사회 영향의 크기\n범위 각 환경/사회 영향이 미치는 지리적/물리적 범위\n교정가능성 부정적 환경/사회 영향을 교정하기 위해 소요되는 기간 \n발생가능성 잠재적 환경/사회 영향이 발생할 것으로 예상되는 기간 \n재무 \n위험/\n기회\n정량적 크기 회사의 매출, 총 자산, 세전이익 등을 고려한 재무 위험/\n기회의 정량적 크기\n정성적 크기 최고경영진의 전략 수립 및 의사결정이 예상 또는 실현되는 \n시기를 고려한 재무 위험/기회의 정성적 크기\n발생가능성 재무 위험/기회가 발생할 것으로 예상되는 기간 \nStep 3. 영향/위험/기회 평가\n삼성전자는 1차 도출 주제별로 파악된 영향 /위험/기회를 평가하기 \n위해 EU ESRS의 요구사 항을 반영하여 평가 척도를 설계하고, 폭넓은 \n이해관계자 참여를 기반으로 평가를 실시했습니다.\n기후변화 및 에너지\n수자원\n자원순환 및 폐기물\n임직원 – 근로조건\n공급망\n정보보호 및 보안\n제품 품질 및 안전\n윤리경영\n최종 중대 주제\n환경 사회 거버넌스',
  "마련하고 유관 사업 활동을 분석하였습니다. 이후 각 활동과 관련성이 높은 \n밸류체인의 사업 활동이 환경과 사회에 미치는 영향을 파악하였습니다. \n또한 각 영향을 긍정과 부정, 실재와 잠재적 영향으로 분류하였습니다. \n아울러 삼성전자는 식별 근거를 토대로 각 주제와 관련한 외부 환경을 \n분석하였으며, 각 영향을 위험과 기회로 분류하고 외부 환경이 회사에 \n재무적으로 미치는 영향을 파악하였습니다.\n이해관계자 참여 기반 평가 \n이해관계자 설문 \n2024년 3월 삼성전자의 임직원, 고객사, 협력회사, 투자사, N GO, 국제기구 등 \n대내외 이해관계자를 대상으로 온라인 설문조사를 실시했습니다. 평가에 참여하는 \n이해관계자의 평가 설문에 대한 이해도를 제고하기 위해 평가 관련 가이드 및 \n영상 자료를 함께 배 포하였습니다. 또한 내부 임직원의 경우, 별도의 설 명회를 \n개최하여 평가 설문 목적, 참여 방법, 평가 척도, 평가 결과의 활용 등을 상세히 \n안내하였습니다.\n경영진 인터뷰 \n2024년 3월 DX/DS부문의 지속가능경영 유관 부서 임원을 대상으로 인터뷰를 \n진행하여 회사에 중요한 ESG 주제에 대한 의견을 청취했습니다.\nEU 이해관계자 포럼\n삼성전자는 2024년 3월 벨 기에 브뤼셀에서 EU 이해관계자 들을 대상으로 \n지속가능경영 포럼 'Innovate & E mpower: Sa msung’s Sustainabil ity \nJourney' 를 개최하였습니다. 이 포럼에는 EFRAG, 유럽 개발청 DG GROW 등 \nEU 정부기관과 ILO, OECD, UNDP, UNEP, UNGC, UN PRI 등 국제기구, RBA, \nWBCSD, GRI 등 협회, 전문기관 등 주요 이해관계자들이 참석하여, 유럽의 비재무 \n공시 기준 및 규제 동향 , 기후 행동, 자원 순환, 노동 인권 분야의 주요 도전 및 \n기회 등에 대해 논의하였습니다. 삼성전자는 참 석한 이해관계자들과의 미팅을 \n통해 삼성전자의 지속가능경영 성과를 공유하고, 유럽 및 글로벌 이해관계자들의",
  'Our Company\n04    CEO 메시지\n05    회사 소개\xa0\n06    이해관계자 소통\n삼성전자 지속가능경영보고서 2024 03Our Company AppendixMateriality Assessment Facts & Figures PrinciplePlanet People',
  "접수된 고충의 처리 원칙에 대한 기준을 수립하였고, 공급망 관리에 \n있어서는 비제조 분야 및 리스크 분석에 따라 제조 분야 2차 협력회사로 \n근로환경 관리 범위를 확대하고 있습니다. 또한 2023년 3월 자회사 형 \n장애인표준사업장 주식 회사 '희망별숲'을 개소하여, 발달 장애인들이 \n삼성전자 임직원에게 제공되는 쿠키 , 머핀 등 제과 제품을 만들 고 \n있습니다. 제과 분야를 시작으로 발달장애인들에게 안정적인 일자리를 \n제공할 예정입니다.\n무엇보다 올해 지속가능경영보고서는 글로벌 공시규제 프레임워크에 \n맞춰, 당사의 주요 지속가능경영 이슈를 발 굴하고, 주요 이슈의 관리 \n체계와 전략, 이행 활동과 현황을 충 실히 전달 하고자 구성하였으며, \n삼성전자의 지속가능경영 웹사이트와도 긴밀히 연계되도록 하였습니다. \n삼성전자는 환경, 사회, 경제적 리스크 와 지정학적 불확실성이 일상이 \n되어버린 시대를 경험 하면서, 지속가능성을 삼성전자가 나아가야할 \n방향의 흔들리지 않는 지표이자, 사업경쟁력과 기술혁신의 원동력으로 \n삼고 있습니다. 어려움은 위대함을 키운다(Difficulty is the Nurse of \nGreatness)는 격언처럼, 삼성전자는 지속가능성을 통해 새로운 도약을 \n모색하고, 더욱 발전하는 모습으로 이해관계자 여러분의 기대에 부응하기 \n위해 최선을 다하겠습니다. \n감사합니다.\n삼성전자주식회사\n 대표이사 부회장\n한종희\n삼성전자주식회사 \nDS부문장 부회장\n전영현\n Our Company",
  '삼성전자 지속가능경영보고서 2024\n06\nOur Company AppendixMateriality Assessment Facts & Figures PrinciplePlanet People\n이해관계자 소통\nStakeholder \nEngagement\n글로벌 기업시민으로서의 책임을 다하기 위해서는 다양한 이해관계자와의 커뮤니케이션이 필수입니다. 삼성전자는 지속가능경영 웹사이트 를 통해 \n관련 정보를 투명하고 신속하게 공개하고 있습니다. 아울러, 이해관계자 포럼, 설문조사, 현장방문을 통한 의견 청취 등 다양한 활동을 통해 이해관계자에게 \n지속가능경영 성과를 공유하고, 의견을 청취하며, 협력관계를 구축하기 위해 노력하고 있습니다.\n이해관계자 중요 관심사 소통 채널 주요 활동\n고객\n(일반 소비자, 거래선)\n·  제품과 서비스 품질\n·  안전한 제품 사용\n·  제품 전 생애주기에서의 환경적 영향\n·  정확한 제품 정보 제공\n·  투명한 커뮤니케이션\n·  고객만족도 조사\n·  컨택센터, 서비스센터\n·  삼성전자 뉴스룸\n· 삼성닷컴\n·  삼성전자 반도체 웹사이트\n·  지속가능경영 웹사이트\n·  영업 채널\n·  제품환경리포트\n·  품질과 안전성 관리체계 강화\n·  국가별 홈페이지 구축하여 제품 정보 제공\n·  고객 VOC 청취 및 해결\n·  사업부 및 주요 사업장에 지속가능성  \n담당 인력 배치\n주주 & 투자자 ·  경제 성과\n·  리스크 관리\n·  정보 공시\n·  ESG 어젠다  \n(환경, 사회, 거버넌스 등)\n·  주주총회\n·  Non-Deal Roadshows, 투자자 미팅\n·  실적발표\n·  Investors Forum\n·  투자자 ESG 로드쇼\n·  IR 웹사이트\n·  경영 실적·전망 발표\n·  주주환원 정책 수립\n·  공시\n· 지배구조 정보 공개\n· 환경·사회 성과 공유\n· 주주·투자자 의견 수렴\n임직원 ·  안전하고 건강한 근로환경\n·  다양성, 형평성, 포용성\n·  교육과 경력개발\n·  고용과 복리후생\n·  노사관계\n·  일하기 좋은 일터'],
 ['· 업종 간 협력\n·  기후 대응을 포함한  \nUN SDGs에 대한 기여\n·  투명하고 신속한 정보 공개\n·  기업 간담회\n·  NGO 미팅\n·  이해관계자 포럼\n·  시민사회 - 경영진 간담회\n·  노동인권 이해관계자 워크샵\n·  지속가능경영 웹사이트\n· 산업협회\n·  글로벌 NGO 대상 의견 수렴\n·  RBA\n1)\n, RMI\n2)\n, BSR\n3)\n 활동\n1) Responsible Business Alliance\n2) Responsible Minerals Initiative\n3) Business for Social Responsibility\n·  UNGC\n1)\n·  ACEC\n2)\n, SCC\n3)\n 활동\n1) United Nations Global Compact\n2) Asia Clean Energy Coalition\n3) Semiconductor Climate Consortium\n정부 ·  간접 경제효과(투자, 고용 등 파생효과)\n·  공정거래\n·  안전·보건\n·  컴플라이언스\n·  기업윤리\n·  정책 간담회\n·  국회\n·  정책수립 공청회\n·  정책자문기구\n·  지속가능경영 웹사이트\n·  정부와 협업하여 중소기업 지원 프로그램 운영 ·  정부와 협업하여 벤처투자 창구 설립·운영\n언론 ·  주요 제품/사업 실적 및 전략\n·  투자, R&D, M&A,  \n신사업 등 미래 성장 전략 \n·  탄소중립 등 ESG 추진 성과\n·  인/노사, 환경안전, 특허,  \n제품·서비스 품질 등\n·  보도자료\n·  지속가능경영 웹사이트\n·  삼성전자 반도체 뉴스룸\n·  삼성전자 뉴스룸\n· 미디어 간담회\n·  글로벌 IT 전시회·신제품 발표 취재지원\n·  미디어데이 개최\n·  기자회견\n·  인터뷰\n·  기획홍보\n Our Company',

In [18]:
for question in df['user_input']:
    an = rag_chain.invoke({"question" : question})
    answer.append(an)

In [19]:
answer[:5]

['The company has included India as one of the global major manufacturing sites where the DX division has achieved 100% renewable energy use for electricity consumption as part of its goal to achieve carbon neutrality by 2030. This initiative contributes to sustainable development by reducing carbon emissions and promoting the use of renewable energy sources in India.',
 '삼성전자는 지속가능경영을 위해 5가지 핵심가치를 수립하였으며, 이 핵심가치를 세부원칙과 행동지침으로 구체화하여 글로벌 행동규범(Global Code of Conduct)을 제정하였습니다. 다만, 구체적인 5가지 핵심가치의 내용은 제공된 문서 내에 명시되어 있지 않습니다.',
 "DRAM is part of Samsung Electronics' DS (Device Solutions) business division, which focuses on semiconductor components. Specifically, DS부문 includes the memory semiconductor business, Foundry business, and System LSI business, producing and selling components such as DRAM, NAND Flash, and mobile AP.",
 'The financial results for SDC in 2023 are not provided in the given context. The sales and operating profit mentioned exclude SDC and Harman.',
 '삼성전자는 다양한 이해관계자와 소통하기 위해 지속가능경영 웹사이트를 통해 관련 정보를 투명하고 신속하게 공개하고 있습니다. 또한, 이해관계자 포럼, 설문조사, 현장방문을 통한 의견 청취 등 다양한 활동을 통해 이해관계자에게 지속가능경영 성과를 공유하고 의견을 청취하며 협력관계를 구축하기 위해 노력하고 있습니다. 주요 소통 채널로는 고객만족도 조사, 컨택센터, 서비스센터, 삼성전자 뉴스룸, 삼성닷컴, 지속가능경영 웹사이트, 주주총회, 투자자 미팅, IR 웹사이트 등이 있으며, 이를 통해 고객, 주주 및 투자자, 임직원 등 다양한 이해관계자의 관심사에 대응하고 있습니다.']

In [26]:
df['response'] = answer
df['retrieved_contexts'] = contexts
df.head()

,user_input,reference_contexts,reference,synthesizer_name,response,retrieved_contexts
0,What initiatives has the company undertaken in...,"[""지속가능한 미래를 위한 노력을 계속해 \n왔습니다. 2050년 탄소중립을 통해 ...","In 인도, the company has transitioned 100% of th...",single_hop_specific_query_synthesizer,The company has included India as one of the g...,[A Journey Towards \na Sustainable Future\n삼성...
1,What are the core values established by 삼성전자 f...,['삼성전자 지속가능경영보고서 2024\n05\nOur Company Appendi...,"삼성전자는 경영철학을 반영한 5가지 핵심가치를 수립하였고, 이를 세부원칙과 행동지침...",single_hop_specific_query_synthesizer,"삼성전자는 지속가능경영을 위해 5가지 핵심가치를 수립하였으며, 이 핵심가치를 세부원...",[A Journey Towards \na Sustainable Future\n삼성...
2,How does DRAM fit into Samsung Electronics' bu...,['Our Company AppendixMateriality Assessment F...,DRAM is part of Samsung Electronics' Device So...,single_hop_specific_query_synthesizer,DRAM is part of Samsung Electronics' DS (Devic...,[삼성전자 지속가능경영보고서 2024\n05\nOur Company Appendix...
3,What are the financial results for SDC in 2023?,"['매출\n169조 9,923억 원\n영업이익\n14조 3,847억 원 네트워크\n...",The financial results for SDC in 2023 indicate...,single_hop_specific_query_synthesizer,The financial results for SDC in 2023 are not ...,[DS Device Solutions\n메모리\n※ 상기 매출과 영업이익은 2023...
4,삼성전자는 어떻게 이해관계자와 소통하나요?,['삼성전자 지속가능경영보고서 2024\n06\nOur Company Appendi...,삼성전자는 이해관계자와의 커뮤니케이션을 위해 지속가능경영 웹사이트를 통해 관련 정보...,single_hop_specific_query_synthesizer,삼성전자는 다양한 이해관계자와 소통하기 위해 지속가능경영 웹사이트를 통해 관련 정보...,[기회 등에 대해 논의하였습니다. 삼성전자는 참 석한 이해관계자들과의 미팅을 \n통...

In [ ]:
df.to_csv("../data/report_2024_answer.csv", index = False)

In [39]:
df = pd.read_csv("../data/report_2024_answer.csv")

In [ ]:
from ast import literal_eval
df['reference_contexts'] = df['reference_contexts'].apply(lambda x: literal_eval(x))
df['retrieved_contexts'] = df['retrieved_contexts'].apply(lambda x: literal_eval(x))

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_input          100 non-null    object
 1   reference_contexts  100 non-null    object
 2   reference           100 non-null    object
 3   synthesizer_name    100 non-null    object
 4   response            100 non-null    object
 5   retrieved_contexts  100 non-null    object
dtypes: object(6)
memory usage: 4.8+ KB

In [47]:
type(df['retrieved_contexts'].iloc[0])

list

In [49]:
type(df['reference'].iloc[0])

str

In [48]:
type(df['reference_contexts'].iloc[0])

list

In [44]:
from ragas import EvaluationDataset, evaluate
from ragas.metrics import Faithfulness, LLMContextRecall, FactualCorrectness
from ragas.llms import LangchainLLMWrapper

# ragas 평가
eval_llm = LangchainLLMWrapper(model)
dataset = EvaluationDataset.from_pandas(df)
dataset

C:\Users\user\AppData\Local\Temp\ipykernel_29936\3001053187.py:6: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use the modern LLM providers instead: from ragas.llms.base import llm_factory; llm = llm_factory('gpt-4o-mini') or from ragas.llms.base import instructor_llm_factory; llm = instructor_llm_factory('openai', client=openai_client)
  eval_llm = LangchainLLMWrapper(model)

EvaluationDataset(features=['user_input', 'retrieved_contexts', 'reference_contexts', 'response', 'reference'], len=100)

In [50]:
scores = evaluate(
    dataset,
    metrics = [Faithfulness(), LLMContextRecall(), FactualCorrectness()],
    llm = eval_llm
)

Evaluating:   0%|          | 0/300 [00:00<?, ?it/s]

Exception raised in Job[71]: TimeoutError()
Exception raised in Job[259]: TimeoutError()
Exception raised in Job[281]: TimeoutError()
Exception raised in Job[298]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Exception raised in Job[296]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Exception raised in Job[285]: TimeoutError()
Exception raised in Job[293]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Exception raised in Job[286]: TimeoutError()
Exception raised in Job[297]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Exception raised in Job[299]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Exception raised in Job[287]: TimeoutError()
Exception raised in Job[290]: TimeoutError()
Exception raised in Job[294]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Exception raised in Job[295]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Exception raised in Job[292]: TimeoutError()

In [51]:
scores

{'faithfulness': 0.9066, 'context_recall': 0.7641, 'factual_correctness(mode=f1)': 0.4110}